
import type { Metadata } from "next";
import { Analytics } from '@vercel/analytics/next';
import "./globals.css";
import localFont from "next/font/local";
import { Inter, DM_Sans } from "next/font/google";
import Providers from "./providers";
import Navbar from "@/components/Landing/Navbar";
import ActiveSectionContextProvider from "@/context/active-section-context";
import Banner from "@/components/Landing/Banner";

const clashgrotesk = localFont({
  src: "../public/fonts/clash-grotesk.woff2",
  style: "normal",
  display: "swap",
  variable: "--font-clashgrotesk"
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
})

const dmsans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dmsans"
}) 

export const metadata: Metadata = {
  title: "Home | HedgeBot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${dmsans.variable} ${clashgrotesk.variable} dark`}>
      <body
        className="font-inter bg-slate-950 min-h-screen"
      >
        <ActiveSectionContextProvider>
        <Providers>
        <Banner />
        <Navbar />
        <main className="mt-18">
        {children}
        </main>
        </Providers>
        <Analytics />
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}
